/*
--------------------------------------------------------------------
Â© 2023 TecnoGlobal All Rights Reserved
--------------------------------------------------------------------
Name   : SG_TELPOP
Link   : https://github.com/oskyba/TG-SG/database
Version: 1.0
--------------------------------------------------------------------
*/

USE [master]
GO

/****** Object:  Database [SG_TELPOP]    Script Date: 02/05/2023 20:18:17 ******/
CREATE DATABASE [SG_TELPOP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SG_TELPOP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SG_TELPOP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SG_TELPOP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SG_TELPOP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SG_TELPOP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SG_TELPOP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SG_TELPOP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SG_TELPOP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SG_TELPOP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SG_TELPOP] SET ARITHABORT OFF 
GO

ALTER DATABASE [SG_TELPOP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SG_TELPOP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SG_TELPOP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SG_TELPOP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SG_TELPOP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SG_TELPOP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SG_TELPOP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SG_TELPOP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SG_TELPOP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SG_TELPOP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SG_TELPOP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SG_TELPOP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SG_TELPOP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SG_TELPOP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SG_TELPOP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SG_TELPOP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SG_TELPOP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SG_TELPOP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SG_TELPOP] SET  MULTI_USER 
GO

ALTER DATABASE [SG_TELPOP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SG_TELPOP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SG_TELPOP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SG_TELPOP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SG_TELPOP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SG_TELPOP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SG_TELPOP] SET QUERY_STORE = ON
GO

ALTER DATABASE [SG_TELPOP] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SG_TELPOP] SET  READ_WRITE 
GO

